---
title: "R Notebook"
output: html_notebook
---


vector is single dimension but array is multiple dimension
```{r Arrays and Vectors}
library(tidyverse)

a = (1:12)
class(a)
c = array((1:12), dim=c(3,4))
class(c)
```

In 4 dimensional array below, a[r,c,r1,c1] r1 and c1 determins the matrix located in row r1 and column c1
of outer most matrix. First two indices r and c are pointing at the element withion the latwr matrix.

```{r arrays}
a = array((1:36), dim=c(2,3,2,3))
dimnames(a) <- list(c("innerRow1","innerRow2"), c("innerCol1", "innerCol2", "innerCol3"), c("row1", "row2"), c("col1", "col2", "col3"))

#    | 1   3   5 | 13   15   17 |  25   27  29 |
#    | 2   4   6 | 14   16   18 |  26   28  30 |
#    ------------------------------------------
#    | 7   9  11 | 19   21   23 | 31   33   35 |
#    | 8  10  12 | 20   22   24 | 32   34   36 |

a
```

```{r}
a[1,1,,]
```

```{r}
a[1,2,,]
```

```{r}
a[1,3,,]
```

```{r}
a[2,1,,]
```


```{r}
a[2,2,,]
```

```{r}
a[2,3,,]
```
```{r}
a[2,3,2,2]
```

